### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tacigar** [tacigar/sceef#15]
- [ ] Vector
    - [ ] Add Vector Expression Class
    - [ ] Add Vector Class
    - [ ] Add Vector Binary Operations
    - [ ] Add Vector Unary Operations
- [ ] Matrix
    - [ ] Add Matrix Expression Class
    - [ ] Add Matrix Class
    - [ ] Add Matrix Binary Operations
    - [ ] Add Matrix Unary Operations
